ML_Website/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),
    path('articles/', include('articles.urls')),
    path('learnings/', include('learnings.urls')),
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep

]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
            {'document_root': os.path.join(BASE_DIR, 'site'),
             'show_indexes': True},
            name='site_path'
            ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'home/static'),
    }
         ),
]

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

home/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view()),


]

learnings/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'learnings'
urlpatterns = [
    path('', views.LearningListView.as_view(), name='all'),
    path('learnings/<int:pk>', views.LearningDetailView.as_view(), name='learning_detail'),
    path('learning/create',
         views.LearningCreateView.as_view(success_url=reverse_lazy('learnings:all')), name='learning_create'),
    path('learnings/<int:pk>/update',
         views.LearningUpdateView.as_view(success_url=reverse_lazy('learnings:all')), name='learning_update'),
    path('learnings/<int:pk>/delete',
         views.LearningDeleteView.as_view(success_url=reverse_lazy('learnings:all')), name='learning_delete'),
    path('learning_picture/<int:pk>', views.stream_file, name='learning_picture'),
    path('learning/<int:pk>/comment',
         views.CommentCreateView.as_view(), name='learning_comment_create'),
    path('comment/<int:pk>/delete',
         views.CommentDeleteView.as_view(success_url=reverse_lazy('learnings')), name='learning_comment_delete'),
    path('learning/<int:pk>/favorite',
         views.AddFavoriteView.as_view(), name='learning_favorite'),
    path('learning/<int:pk>/unfavorite',
         views.DeleteFavoriteView.as_view(), name='learning_unfavorite'),
]

learnings/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.conf import settings


class Learning(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()

    # https://django-taggit.readthedocs.io/en/latest/api.html#TaggableManager
    tags = TaggableManager(blank=True)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       through='Fav', related_name='favorite_learnings')
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                      through='Comment', related_name='comments_owned')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')

    # Shows up in the admin list
    def __str__(self):
        return self.title


class Fav(models.Model):
    learning = models.ForeignKey(Learning, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/4.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('learning', 'user')

    def __str__(self):
        return '%s likes %s' % (self.user.username, self.learning.title[:10])


class Comment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    learning = models.ForeignKey(Learning, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15: return self.text
        return self.text[:11] + ' ...'

######################################################

learnings/forms.py
from django import forms
from learnings.models import Learning
from django.core.files.uploadedfile import InMemoryUploadedFile
from learnings.humanize import naturalsize


# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= ' + max_upload_limit_text)
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Learning
        fields = ['title', 'text', 'picture', 'price', 'tags']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < " + self.max_upload_limit_text + " bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture  # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
            self.save_m2m()  # Add this

        return instance


class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

learnings/views.py
from learnings.models import Learning, Comment, Fav
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from learnings.forms import CreateForm, CommentForm
from learnings.owner import OwnerListView, OwnerDeleteView
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q


####################################
class PostListView(View):
    model = Learning
    template_name = "learnings/learning_list.html"

    def get(self, request):
        strval = request.GET.get("search", False)
        if strval:
            # Simple title-only search
            # objects = Post.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            # __icontains for case-insensitive search
            query = Q(title__icontains=strval)
            query.add(Q(text__icontains=strval), Q.OR)
            learning_list = Learning.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else:
            learning_list = Learning.objects.all().order_by('-updated_at')[:10]

        # Augment the post_list
        for obj in learning_list:
            obj.natural_updated = naturaltime(obj.updated_at)

        ctx = {'learning_list': learning_list, 'search': strval}
        return render(request, self.template_name, ctx)


###################################################

class LearningListView(OwnerListView):
    model = Learning
    # By convention:
    template_name = "learnings/learning_list.html"

    def get(self, request):
        strval = request.GET.get("search", False)
        if strval:

            query = Q(title__icontains=strval)
            query.add(Q(text__icontains=strval), Q.OR)
            learning_list = Learning.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else:
            learning_list = Learning.objects.all().order_by('-updated_at')[:10]

        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_learnings.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [row['id'] for row in rows]
        ctx = {'learning_list': learning_list, 'search': strval, 'favorites': favorites}
        return render(request, self.template_name, ctx)


class LearningDetailView(OwnerListView):
    model = Learning
    template_name = "learnings/learning_detail.html"

    def get(self, request, pk):
        x = Learning.objects.get(id=pk)
        comments = Comment.objects.filter(learning=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = {'learning': x, 'comments': comments, 'comment_form': comment_form}
        return render(request, self.template_name, context)


class LearningCreateView(LoginRequiredMixin, View):
    template_name = 'learnings/learning_form.html'
    success_url = reverse_lazy('learnings:all')
    fields = ['title', 'price', 'text', 'picture']

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        learning = form.save(commit=False)
        learning.owner = self.request.user
        learning.save()

        # Adjust the model owner before saving
        inst = form.save(commit=False)
        inst.owner = self.request.user
        inst.save()

        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        form.save_m2m()  # Add this

        return redirect(self.success_url)


class LearningUpdateView(LoginRequiredMixin, View):
    template_name = 'learnings/learning_form.html'
    success_url = reverse_lazy('learnings:all')
    fields = ['title', 'price', 'text', 'picture']

    def get(self, request, pk):
        pic = get_object_or_404(Learning, id=pk, owner=self.request.user)
        form = CreateForm(instance=pic)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        learning = get_object_or_404(Learning, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=learning)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        learning = form.save(commit=False)
        learning.save()

        # Adjust the model owner before saving
        inst = form.save(commit=False)
        inst.owner = self.request.user
        inst.save()

        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        form.save_m2m()  # Add this

        return redirect(self.success_url)


class LearningDeleteView(OwnerDeleteView):
    model = Learning
    template_name = "learnings/learning_confirm_delete.html"


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk):
        la = get_object_or_404(Learning, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, learning=la)
        comment.save()
        return redirect(reverse('learnings:learning_detail', args=[pk]))


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "learnings/comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        learning = self.object.learning
        return reverse('learnings:learning_detail', args=[learning.id])


def stream_file(request, pk):
    learning = get_object_or_404(Learning, id=pk)
    response = HttpResponse()
    response['Content-Type'] = learning.content_type
    response['Content-Length'] = len(learning.picture)
    response.write(learning.picture)
    return response


from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError


@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        print("Add PK", pk)
        t = get_object_or_404(Learning, id=pk)
        fav = Fav(user=request.user, learning=t)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()


@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        print("Delete PK", pk)
        t = get_object_or_404(Learning, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, learning=t).delete()
        except Fav.DoesNotExist as e:
            pass

        return HttpResponse()

learnings/templates/learnings/comment_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'learnings:learning_detail' comment.learning.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

learnings/templates/learnings/learning_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Learning</h1>

<p>Are you sure you want to delete the learning : {{ learning }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

learnings/templates/learnings/learning_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% block content %}
{% if learning.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'learnings:learning_picture' learning.id %}">
</div>
{% endif %}
<span style="float: right;">
({{ learning.updated_at|naturaltime }})
{% if learning.owner == user %}
<a href="{% url 'learnings:learning_update' learning.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'learnings:learning_delete' learning.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ learning.title }}</h1>
{% if learning.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'learnings:learning_picture' learning.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}
<p>
{{ learning.text }}
({{ learning.updated_at|naturaltime }})
</p>
{% if user.is_authenticated %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'learnings:learning_comment_create' learning.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="All Learnings" onclick="window.location.href='{% url 'learnings:all' %}';return false;">
</form>
</p>
{% endif %}
{% for comment in comments %}
<p> {{ comment.text }}
({{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'learnings:learning_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</p>
{% endfor %}
{% endblock %}

learnings/templates/learnings/learning_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block content %}

<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'learnings:all' %}';return false;">
  </form>
</p>
<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

learnings/templates/learnings/learning_list.html
{% extends "base_page.html" %}
{% block content %}
<h1>Learnings</h1>
<div style="float:right">
<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}
  >
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'learnings:all' %}"><i class="fa fa-undo"></i></a>
</form>
</div>
<p>
{% if learning_list %}
<ul>
  {% for learning in learning_list %}
    <li>
        <a href="{% url 'learnings:learning_detail'  learning.id %}">{{ learning.title }}</a>
        {% if learning.owner == user %}
        (<a href="{% url 'learnings:learning_update' learning.id %}">Edit</a> |
        <a href="{% url 'learnings:learning_delete' learning.id %}">Delete</a>)
        {% endif %}
        {% if user.is_authenticated %}
        <a href="#" onclick=
            "favPost('{% url 'learnings:learning_unfavorite' learning.id %}', {{ learning.id }} );return false;"
            {% if learning.id not in favorites %} style="display: none;" {% endif %}
            id="favorite_star_{{learning.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        <!-- the second href -->
        <a href="#" onclick=
             "favPost('{% url 'learnings:learning_favorite' learning.id %}', {{ learning.id }} );return false;"
            {% if learning.id in favorites %} style="display: none;" {% endif %}
            id="unfavorite_star_{{learning.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no learning articles in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'learnings:learning_create' %}">Add a learning</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'learnings:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'learnings:all' %}">Login</a>
{% endif %}
</p>
<script>
function favPost(url, learning_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+learning_id).toggle();
        $("#favorite_star_"+learning_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
{% endblock %}