ML_Website/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('home.urls')),
    path('articles/', include('articles.urls')),
    path('learnings/', include('learnings.urls')),
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep

]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
            {'document_root': os.path.join(BASE_DIR, 'site'),
             'show_indexes': True},
            name='site_path'
            ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'home/static'),
    }
         ),
]

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

articles/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'articles'
urlpatterns = [
    path('', views.ArticleListView.as_view(), name='all'),
    path('articles/<int:pk>', views.ArticleDetailView.as_view(), name='article_detail'),
    path('article/<int:pk>/articlecomment',
         views.ArticleCommentCreateView.as_view(), name='article_comment_create'),
    path('articlecomment/<int:pk>/delete',
         views.ArticleCommentDeleteView.as_view(success_url=reverse_lazy('articles')), name='article_comment_delete'),
    path('article/<int:pk>/articlefavorite',
         views.ArticleAddFavoriteView.as_view(), name='article_favorite'),
    path('article/<int:pk>/articleunfavorite',
         views.ArticleDeleteFavoriteView.as_view(), name='article_unfavorite'),
]

home/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view()),


]

articles/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.conf import settings


class Article(models.Model):
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    # price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    gist_link = models.TextField()

    # https://django-taggit.readthedocs.io/en/latest/api.html#TaggableManager
    tags = TaggableManager(blank=True)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       through='ArticleFav', related_name='favorite_articles')
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                      through='ArticleComment', related_name='article_comments_owned')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return self.title


class ArticleFav(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/4.0/ref/models/options/#unique-together
    class Meta:
        unique_together = ('article', 'user')

    def __str__(self):
        return '%s likes %s' % (self.user.username, self.article.title[:10])


class ArticleComment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15: return self.text
        return self.text[:11] + ' ...'


######################################################
from django.db import models

# Create your models here.

articles/forms.py
from django import forms
from articles.models import Article
from django.core.files.uploadedfile import InMemoryUploadedFile
from learnings.humanize import naturalsize


class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

articles/views.py
from articles.models import Article, ArticleComment, ArticleFav
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from articles.forms import CommentForm
from articles.owner import OwnerListView, OwnerDeleteView
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q


class PostListView(View):
    model = Article
    template_name = "articles/article_list.html"

    def get(self, request):
        strval = request.GET.get("search", False)
        if strval:
            # Simple title-only search
            # objects = Post.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            # __icontains for case-insensitive search
            query = Q(title__icontains=strval)
            query.add(Q(text__icontains=strval), Q.OR)
            article_list = Article.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else:
            article_list = Article.objects.all().order_by('-updated_at')[:10]

        # Augment the post_list
        for obj in article_list:
            obj.natural_updated = naturaltime(obj.updated_at)

        ctx = {'article_list': article_list, 'search': strval}
        return render(request, self.template_name, ctx)


###################################################

class ArticleListView(OwnerListView):
    model = Article
    # By convention:
    template_name = "articles/article_list.html"

    def get(self, request):
        strval = request.GET.get("search", False)
        if strval:

            query = Q(title__icontains=strval)
            query.add(Q(text__icontains=strval), Q.OR)
            article_list = Article.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else:
            article_list = Article.objects.all().order_by('-updated_at')[:10]

        favorite_articles = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_articles.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [row['id'] for row in rows]
        ctx = {'article_list': article_list, 'search': strval, 'favorite articles': favorite_articles}
        return render(request, self.template_name, ctx)


class ArticleDetailView(OwnerListView):
    model = Article
    template_name = "articles/article_detail.html"

    def get(self, request, pk):
        x = Article.objects.get(id=pk)
        article_comments = ArticleComment.objects.filter(article=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = {'article': x, 'comments': article_comments, 'comment_form': comment_form}
        return render(request, self.template_name, context)


class ArticleCommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk):
        a = get_object_or_404(Article, id=pk)
        article_comment = ArticleComment(text=request.POST['comment'], owner=request.user, article=a)
        article_comment.save()
        return redirect(reverse('articles:article_detail', args=[pk]))

class ArticleCommentDeleteView(OwnerDeleteView):
    model = ArticleComment
    template_name = "articles/articlecomment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        article = self.object.article
        return reverse('articles:article_detail', args=[article.id])


def stream_file(request, pk):
    article = get_object_or_404(Article, id=pk)
    response = HttpResponse()
    response['Content-Type'] = article.content_type
    response['Content-Length'] = len(article.picture)
    response.write(article.picture)
    return response


from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError


@method_decorator(csrf_exempt, name='dispatch')
class ArticleAddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        print("Add PK", pk)
        t = get_object_or_404(Article, id=pk)
        articlefav = ArticleFav(user=request.user, article=t)
        try:
            articlefav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()


@method_decorator(csrf_exempt, name='dispatch')
class ArticleDeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        print("Delete PK", pk)
        t = get_object_or_404(Article, id=pk)
        try:
            articlefav = ArticleFav.objects.get(user=request.user, article=t).delete()
        except ArticleFav.DoesNotExist as e:
            pass

        return HttpResponse()

articles/templates/articles/about_me.html
{% extends "Selecao/inner-page.html" %}
{% block main %}

<main id="main">
    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>About me and MLNow</h2>
          <ol>
            <li><a href="/home/main">Home</a></li>
            <li>About me and MLNow</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <div class="container">
        <p>
          This project is for the benefit of myself and anyone trying to learn about similar things.
    I hope to organize this site as a way of displaying what I have learned / done. In
    scientific studies and anecdotally, teaching is the best way to solidify learning. This site hopes to accomplish that for me
    as I try to explain what I have learned in my own words, as well as implement in examples.
        </p>
          <p>
              One of the goals of this site is to study for the google tensorflow exam.
              I believe that independent certifications like this will start to rival
              and replace a formal college education. I have taken a number of coursera courses,
              and hope to turn what I've learned into projects displayed here.
          </p>
      </div>
    </section>
</main>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends "base_page.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}

<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% block content %}
<span style="float: right;">
({{ article.updated_at|naturaltime }})
</span>
<h1>{{ article.title }}</h1>
<p>
{{ article.text }}
({{ article.updated_at|naturaltime }})
</p>
<p>
</p>
<p>
</p>
<p>
<script src="{{article.gist_link}}.js"></script>
</p>
{% if user.is_authenticated %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'articles:article_comment_create' article.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="All Articles" onclick="window.location.href='{% url 'articles:all' %}';return false;">
</form>
</p>
{% endif %}
{% for comment in comments %}
<p> {{ comment.text }}
({{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'articles:article_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</p>
{% endfor %}




{% endblock %}

articles/templates/articles/article_list.html
{% extends "base_page.html" %}
{% block content %}
<h1>Articles</h1>
<div style="float:right">
<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}
  >
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'articles:all' %}"><i class="fa fa-undo"></i></a>
</form>
</div>
<p>
{% if article_list %}
<ul>
  {% for article in article_list %}
    <li>
        <a href="{% url 'articles:article_detail'  article.id %}">{{ article.title }}</a>
        {% if user.is_authenticated %}
        <a href="#" onclick=
            "favPost('{% url 'articles:article_unfavorite' article.id %}', {{ article.id }} );return false;"
            {% if learning.id not in favorites %} style="display: none;" {% endif %}
            id="favorite_star_{{learning.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        <!-- the second href -->
        <a href="#" onclick=
             "favPost('{% url 'articles:article_favorite' article.id %}', {{ article.id }} );return false;"
            {% if article.id in favorites %} style="display: none;" {% endif %}
            id="unfavorite_star_{{article.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no learning articles in the database.</p>
{% endif %}
</p>
<p>
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'articles:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'articles:all' %}">Login</a>
{% endif %}
</p>
<script>
function favPost(url, learning_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+learning_id).toggle();
        $("#favorite_star_"+learning_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
{% endblock %}

articles/templates/articles/articlecomment_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ articlecomment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'articles:article_detail' articlecomment.article.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

articles/templates/articles/sample_iframe.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% block content %}

        <p>
          This project is for the benefit of myself and anyone trying to learn about similar things.
    I hope to organize this site as a way of displaying what I have learned / done. In
    scientific studies and anecdotally, teaching is the best way to solidify learning. This site hopes to accomplish that for me
    as I try to explain what I have learned in my own words, as well as implement in examples.
        </p>
          <p>
              <script src="https://gist.github.com/JackMayr2/0cd2b53df432cd3eed04bdd7a6ea49b7.js"></script>
          </p>

{% endblock %}